"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.BUTTON_WIDTH = exports.BUTTON_TEXT_SIZE = exports.BUTTON_TEXT_FONT = exports.BUTTON_TEXT_COLOR = exports.BUTTON_TEXT = exports.BUTTON_MARGIN_TOP = exports.BUTTON_MARGIN_LEFT = exports.BUTTON_HEIGHT = exports.BUTTON_COLOR = exports.BUTTON_BORDER_WIDTH = exports.BUTTON_BORDER_RADIUS = exports.BUTTON_BORDER_COLOR = void 0;
const BUTTON_COLOR = '#026cff';
exports.BUTTON_COLOR = BUTTON_COLOR;
const BUTTON_TEXT = 'Pay';
exports.BUTTON_TEXT = BUTTON_TEXT;
const BUTTON_TEXT_FONT = 'Roboto';
exports.BUTTON_TEXT_FONT = BUTTON_TEXT_FONT;
const BUTTON_TEXT_SIZE = 15;
exports.BUTTON_TEXT_SIZE = BUTTON_TEXT_SIZE;
const BUTTON_TEXT_COLOR = '#ffffff';
exports.BUTTON_TEXT_COLOR = BUTTON_TEXT_COLOR;
const BUTTON_HEIGHT = 30;
exports.BUTTON_HEIGHT = BUTTON_HEIGHT;
const BUTTON_WIDTH = 40;
exports.BUTTON_WIDTH = BUTTON_WIDTH;
const BUTTON_MARGIN_TOP = 50;
exports.BUTTON_MARGIN_TOP = BUTTON_MARGIN_TOP;
const BUTTON_MARGIN_LEFT = 130;
exports.BUTTON_MARGIN_LEFT = BUTTON_MARGIN_LEFT;
const BUTTON_BORDER_WIDTH = 0;
exports.BUTTON_BORDER_WIDTH = BUTTON_BORDER_WIDTH;
const BUTTON_BORDER_RADIUS = 0;
exports.BUTTON_BORDER_RADIUS = BUTTON_BORDER_RADIUS;
const BUTTON_BORDER_COLOR = '#000000';
exports.BUTTON_BORDER_COLOR = BUTTON_BORDER_COLOR;
//# sourceMappingURL=buttonConstants.js.map