"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DIRECT_PAY_VIEW_WIDTH = exports.DIRECT_PAY_VIEW_HEIGHT = exports.CUSTOM_UI_VIEW_WIDTH = exports.CUSTOM_UI_VIEW_HEIGHT = void 0;
const CUSTOM_UI_VIEW_HEIGHT = 500;
exports.CUSTOM_UI_VIEW_HEIGHT = CUSTOM_UI_VIEW_HEIGHT;
const CUSTOM_UI_VIEW_WIDTH = 320;
exports.CUSTOM_UI_VIEW_WIDTH = CUSTOM_UI_VIEW_WIDTH;
const DIRECT_PAY_VIEW_HEIGHT = 300;
exports.DIRECT_PAY_VIEW_HEIGHT = DIRECT_PAY_VIEW_HEIGHT;
const DIRECT_PAY_VIEW_WIDTH = 300;
exports.DIRECT_PAY_VIEW_WIDTH = DIRECT_PAY_VIEW_WIDTH;
//# sourceMappingURL=styleDefaults.js.map